//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.LocalActivityServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityData", Namespace="http://schemas.datacontract.org/2004/07/ActivityServiceWebRole")]
    [System.SerializableAttribute()]
    public partial class ActivityData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DateTimeStampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DateTimeStamp {
            get {
                return this.DateTimeStampField;
            }
            set {
                if ((this.DateTimeStampField.Equals(value) != true)) {
                    this.DateTimeStampField = value;
                    this.RaisePropertyChanged("DateTimeStamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocalActivityServiceReference.IActivityDetailsService")]
    public interface IActivityDetailsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityDetailsService/CheckService", ReplyAction="http://tempuri.org/IActivityDetailsService/CheckServiceResponse")]
        string CheckService(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityDetailsService/CheckService", ReplyAction="http://tempuri.org/IActivityDetailsService/CheckServiceResponse")]
        System.Threading.Tasks.Task<string> CheckServiceAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityDetailsService/GetActivityDetails", ReplyAction="http://tempuri.org/IActivityDetailsService/GetActivityDetailsResponse")]
        TestConsole.LocalActivityServiceReference.ActivityData[] GetActivityDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IActivityDetailsService/GetActivityDetails", ReplyAction="http://tempuri.org/IActivityDetailsService/GetActivityDetailsResponse")]
        System.Threading.Tasks.Task<TestConsole.LocalActivityServiceReference.ActivityData[]> GetActivityDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActivityDetailsServiceChannel : TestConsole.LocalActivityServiceReference.IActivityDetailsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivityDetailsServiceClient : System.ServiceModel.ClientBase<TestConsole.LocalActivityServiceReference.IActivityDetailsService>, TestConsole.LocalActivityServiceReference.IActivityDetailsService {
        
        public ActivityDetailsServiceClient() {
        }
        
        public ActivityDetailsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivityDetailsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityDetailsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityDetailsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckService(string value) {
            return base.Channel.CheckService(value);
        }
        
        public System.Threading.Tasks.Task<string> CheckServiceAsync(string value) {
            return base.Channel.CheckServiceAsync(value);
        }
        
        public TestConsole.LocalActivityServiceReference.ActivityData[] GetActivityDetails() {
            return base.Channel.GetActivityDetails();
        }
        
        public System.Threading.Tasks.Task<TestConsole.LocalActivityServiceReference.ActivityData[]> GetActivityDetailsAsync() {
            return base.Channel.GetActivityDetailsAsync();
        }
    }
}
